CREATE TABLE IF NOT EXISTS public.buyers (
    id SERIAL PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    phone_number TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    budget DECIMAL,
    preferred_location TEXT,
    bedrooms_required INTEGER,
    bathrooms_required INTEGER,
    is_premium BOOLEAN,
    notes TEXT,
    status INTEGER,
    registration_date TIMESTAMP WITH TIME ZONE,
    user_id TEXT,
    created_by TEXT NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL,
    last_modified_by TEXT NOT NULL,
    last_modified_on TIMESTAMP WITH TIME ZONE,
    deleted_by TEXT,
    deleted_on TIMESTAMP WITH TIME ZONE
);
